[package]
name = "soil-api-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.209", features = ["derive"] }
axum = "0.7.5"
dotenvy = "0.15.7"
# geo-types = { version = "0.7.13", features = ["serde"] }
serde_json = "1.0.128"
sqlx = { version = "0.8.2", features = [
    "postgres",
    "runtime-tokio-native-tls",
    "macros",
    "uuid",
    "chrono",
] }
tokio = { version = "1.40.0", features = ["full"] }
hyper = "1.4.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = { version = "1.10.0", features = ["serde"] }
chrono = { version = "0.4.38", features = ["serde"] }
sea-orm = {version = "1.0.1", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"], default-features = false}
sea-orm-migration = "1.0.1"
# proj = "0.27.2"
# wkt = "0.11.0"
