[package]
name = "soil-api-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["macros"] }
dotenvy = "0.15.7"
serde = { version = "1.0.217", features = ["derive"] }
# geo-types = { version = "0.7.13", features = ["serde"] }
serde_json = "1.0.137"
# sqlx = { version = "0.7.4", features = [
#     "postgres",
#     "runtime-tokio-native-tls",
#     "macros",
#     "uuid",
#     "chrono",
#     # "sqlite",
# ], default-features = false }
tokio = { version = "1.43.0", features = ["full"] }
hyper = "1.5.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
uuid = { version = "1.12.1", features = ["serde", "v4", "fast-rng"] }
chrono = { version = "0.4.39", features = ["serde"] }
sea-orm = { version = "1.1.4", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
    "with-uuid",
    "with-chrono",
    "with-json",
], default-features = false }
sea-orm-migration = "1.1.4"
# proj = "0.27.2"
wkt = { version = "0.12.0", features = ["serde", "geo-types"] }
geozero = { version = "0.14.0", features = ["with-postgis-sqlx"] }
geo-types = { version = "0.7.15", features = ["serde"] }
utoipa = { version = "5.3.1", features = ["axum_extras", "uuid", "chrono"] }
# sea-query = "0.31.0"
# utoipa-axum = "0.1.0-beta.2"
utoipa-swagger-ui = { version = "9.0.0", features = ["axum"] }
utoipa-redoc = { version = "6.0.0", features = ["axum"] }
utoipa-rapidoc = { version = "6.0.0", features = ["axum"] }
utoipa-scalar = { version = "0.3.0", features = ["axum"] }
wkb = "0.8.0"
byteorder = "1.5.0"
lttb = "0.2.0"
futures = "0.3.31"
serde_with = "3.10.0"
tower-http = { version = "0.6.2", features = ["trace"] }
axum-keycloak-auth = "0.7.0"
itertools = "0.14.0"
async-trait = "0.1.85"
rand = "0.9.0"

[dev-dependencies]
tower = { version = "0.5.2", features = ["util"] }
sea-orm = { version = "1.0.1", features = [
    "sqlx-postgres",
    "sqlx-sqlite",
    "runtime-tokio-rustls",
    "macros",
    "with-uuid",
    "with-chrono",
    "with-json",
], default-features = false }
rstest = "0.24.0"
async-std = { version = "1.13", features = ["attributes"] }
