FROM rust:1.84.0

RUN cargo install bacon
WORKDIR /app

COPY Cargo.lock Cargo.toml bacon.toml /app/
COPY ./migration/ /app/migration/
COPY ./crudcrate/ /app/crudcrate/
COPY ./crudcrate-derive/ /app/crudcrate-derive/
COPY ./src/ /app/src/

ENTRYPOINT ["bacon", "--headless", "run"]
