FROM rust:1.85.0

RUN cargo install bacon
WORKDIR /app

# Install python 3.11
RUN apt-get update && apt-get install -y python3.11 python3-pip

COPY Cargo.lock Cargo.toml bacon.toml /app/
COPY ./migration/ /app/migration/
COPY ./src/ /app/src/

ENTRYPOINT ["bacon", "--headless", "run"]
