"""Add plot:sensor link

Revision ID: 20c57bba555c
Revises: 376634bd3252
Create Date: 2024-09-05 10:32:35.949724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '20c57bba555c'
down_revision: Union[str, None] = '376634bd3252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plotsensorassignments',
    sa.Column('date_from', sa.DateTime(), nullable=False),
    sa.Column('date_to', sa.DateTime(), nullable=False),
    sa.Column('plot_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('sensor_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('iterator', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plot.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('iterator'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_plotsensorassignments_id'), 'plotsensorassignments', ['id'], unique=False)
    op.create_index(op.f('ix_plotsensorassignments_iterator'), 'plotsensorassignments', ['iterator'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plotsensorassignments_iterator'), table_name='plotsensorassignments')
    op.drop_index(op.f('ix_plotsensorassignments_id'), table_name='plotsensorassignments')
    op.drop_table('plotsensorassignments')
    # ### end Alembic commands ###
