"""Add depth property to plot:sensor relationship

Revision ID: c7c4c9c065e0
Revises: 20c57bba555c
Create Date: 2024-09-05 12:29:25.869575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c7c4c9c065e0'
down_revision: Union[str, None] = '20c57bba555c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plotsensorassignments', sa.Column('depth_cm', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plotsensorassignments', 'depth_cm')
    # ### end Alembic commands ###
