//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub mod prelude;

pub mod alembic_version;
pub mod area;
pub mod cake;
pub mod cake_filling;
pub mod filling;
pub mod fruit;
pub mod gnss;
pub mod instrumentexperiment;
pub mod instrumentexperimentchannel;
pub mod plot;
pub mod plotsample;
pub mod plotsensorassignments;
pub mod posts;
pub mod project;
pub mod sea_orm_active_enums;
pub mod sensor;
pub mod sensordata;
pub mod soilprofile;
pub mod soiltype;
pub mod spatial_ref_sys;
pub mod transect;
pub mod transectnode;
