//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use uuid::Uuid;
use chrono::NaiveDateTime;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "plotsensorassignments")]
pub struct Model {
    pub date_from: NaiveDateTime,
    pub date_to: NaiveDateTime,
    pub plot_id: Uuid,
    pub sensor_id: Uuid,
    #[sea_orm(primary_key)]
    pub iterator: i32,
    #[sea_orm(unique)]
    pub id: Uuid,
    pub depth_cm: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::plot::Entity",
        from = "Column::PlotId",
        to = "super::plot::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Plot,
    #[sea_orm(
        belongs_to = "super::sensor::Entity",
        from = "Column::SensorId",
        to = "super::sensor::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Sensor,
}

impl Related<super::plot::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plot.def()
    }
}

impl Related<super::sensor::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sensor.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
