//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use chrono::NaiveDateTime;
// use geo::Geometry;
use sea_orm::entity::prelude::*;
use uuid::Uuid;
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sensor")]
pub struct Model {
    pub name: Option<String>,
    pub description: Option<String>,
    pub comment: Option<String>,
    #[sea_orm(primary_key)]
    pub iterator: i32,
    #[sea_orm(unique)]
    pub id: Uuid,
    // #[sea_orm(column_type = "custom(\"geometry\")", nullable)]
    // pub geom: Option<String>,
    pub area_id: Uuid,
    pub last_updated: NaiveDateTime,
    pub serial_number: Option<String>,
    pub manufacturer: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::area::Entity",
        from = "Column::AreaId",
        to = "super::area::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Area,
    #[sea_orm(has_many = "super::plotsensorassignments::Entity")]
    Plotsensorassignments,
    #[sea_orm(has_many = "super::sensordata::Entity")]
    Sensordata,
}

impl Related<super::area::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Area.def()
    }
}

impl Related<super::plotsensorassignments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plotsensorassignments.def()
    }
}

impl Related<super::sensordata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sensordata.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
