//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use uuid::Uuid;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "transectnode")]
pub struct Model {
    pub plot_id: Uuid,
    pub transect_id: Uuid,
    pub order: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::plot::Entity",
        from = "Column::PlotId",
        to = "super::plot::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Plot,
    #[sea_orm(
        belongs_to = "super::transect::Entity",
        from = "Column::TransectId",
        to = "super::transect::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Transect,
}

impl Related<super::plot::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plot.def()
    }
}

impl Related<super::transect::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transect.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
